# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()

a1 = np.array([1,2,3])
# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],
               [4,5,6]])
# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape,a1.ndim,a1.dtype,a1.size,type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [5]:
# Attributes of 2-dimensional array
a2.shape,a2.ndim,a2.dtype,a2.size,type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [6]:
# Attributes of 3-dimensional array
a3.shape,a3.ndim,a3.dtype,a3.size,type(a3)

((2, 3, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [8]:
# Create an array of shape (10, 2) with only ones
ones = np.ones(shape= (10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros(shape = (7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0,100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [11]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(low = 0,high = 10,size = (7,2))
random_array

array([[9, 4],
       [4, 0],
       [2, 1],
       [0, 5],
       [9, 7],
       [0, 7],
       [0, 1]])

In [12]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_float_array = np.random.random(size = (3,5))
random_float_array

array([[0.35778305, 0.40886769, 0.48414887, 0.34221625, 0.88917809],
       [0.64815611, 0.03099231, 0.64347257, 0.44136277, 0.64837491],
       [0.2850512 , 0.46016633, 0.08076928, 0.36743317, 0.49813246]])

In [14]:
# Set the random seed to 42

np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_seed42 = np.random.randint(low = 0,high = 10,size = (4,6))
random_array_seed42

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [20]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

array = np.random.randint(low = 0,high = 10,size = (3,7))
# Find the unique numbers in the array you just created
array,np.unique(array)

(array([[5, 2, 0, 2, 4, 2, 0],
        [4, 9, 6, 6, 8, 9, 9],
        [2, 6, 0, 3, 3, 4, 6]]),
 array([0, 2, 3, 4, 5, 6, 8, 9]))

In [21]:
# Find the 0'th index of the latest array you created
array[0]

array([5, 2, 0, 2, 4, 2, 0])

In [22]:
# Get the first 2 rows of latest array you created
array[:2]

array([[5, 2, 0, 2, 4, 2, 0],
       [4, 9, 6, 6, 8, 9, 9]])

In [23]:
# Get the first 2 values of the first 2 rows of the latest array
array[:2,:2]

array([[5, 2],
       [4, 9]])

In [29]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
np.random.seed(0)
random_test_array = np.random.randint(low  =0,high = 10,size = (3,5))
ones_array1 = np.ones(shape= (3,5))
random_test_array,ones_array

(array([[5, 0, 3, 3, 7],
        [9, 3, 5, 2, 4],
        [7, 6, 8, 8, 1]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [30]:
# Add the two arrays together
random_test_array  + ones_array1

array([[ 6.,  1.,  4.,  4.,  8.],
       [10.,  4.,  6.,  3.,  5.],
       [ 8.,  7.,  9.,  9.,  2.]])

In [31]:
# Create another array of ones of shape (5, 3)
ones_array2 = np.ones(shape= (5,3))
ones_array2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
# Try add the array of ones and the other most recent array together
#random_test_array  + ones_array2

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [35]:
# Create another array of ones of shape (3, 5)
ones_array3 = np.ones(shape= (3,5))

In [36]:
# Subtract the new array of ones from the other most recent array
random_test_array  - ones_array3

array([[ 4., -1.,  2.,  2.,  6.],
       [ 8.,  2.,  4.,  1.,  3.],
       [ 6.,  5.,  7.,  7.,  0.]])

In [37]:
# Multiply the ones array with the latest array
ones_array3 * random_test_array

array([[5., 0., 3., 3., 7.],
       [9., 3., 5., 2., 4.],
       [7., 6., 8., 8., 1.]])

In [38]:
# Take the latest array to the power of 2 using '**'
random_test_array ** 2

array([[25,  0,  9,  9, 49],
       [81,  9, 25,  4, 16],
       [49, 36, 64, 64,  1]])

In [39]:
# Do the same thing with np.square()
np.square(random_test_array)

array([[25,  0,  9,  9, 49],
       [81,  9, 25,  4, 16],
       [49, 36, 64, 64,  1]])

In [40]:
# Find the mean of the latest array using np.mean()
np.mean(random_test_array)

4.733333333333333

In [41]:
# Find the maximum of the latest array using np.max()
np.max(random_test_array)

9

In [42]:
# Find the minimum of the latest array using np.min()
np.min(random_test_array)

0

In [43]:
# Find the standard deviation of the latest array
np.std(random_test_array)

2.6449112566503166

In [44]:
# Find the variance of the latest array
np.var(random_test_array)

6.995555555555556

In [46]:
# Reshape the latest array to (3, 5, 1)
random_test_array.reshape(3,5,1)

array([[[5],
        [0],
        [3],
        [3],
        [7]],

       [[9],
        [3],
        [5],
        [2],
        [4]],

       [[7],
        [6],
        [8],
        [8],
        [1]]])

In [47]:
# Transpose the latest array
random_test_array.T

array([[5, 9, 7],
       [0, 3, 6],
       [3, 5, 8],
       [3, 2, 8],
       [7, 4, 1]])

What does the transpose do?

In [51]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
np.random.seed(0)
a1 = np.random.randint(low = 0,high =10,size = (3,3))
a2 = np.random.randint(low = 0,high =10,size = (3,2))
a1,a2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2]]),
 array([[4, 7],
        [6, 8],
        [8, 1]]))

In [52]:
# Perform a dot product on the two newest arrays you created
a1.dot(a2)

array([[ 44,  38],
       [126,  86],
       [ 58,  63]])

In [53]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
np.random.seed(0)
a3 = np.random.randint(low = 0,high =10,size = (4,3))
a4 = np.random.randint(low = 0,high =10,size = (4,3))
a3,a4

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6]]),
 array([[8, 8, 1],
        [6, 7, 7],
        [8, 1, 5],
        [9, 8, 9]]))

In [56]:
# Perform a dot product on the two newest arrays you created
# a3.dot(a4)

It doesn't work. How would you fix it?

In [57]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
a3.dot(a4.T)

array([[ 43,  51,  55,  72],
       [ 89, 130,  76, 164],
       [ 66,  67,  39,  85],
       [ 94, 115,  69, 146]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [63]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
np.random.seed(10)
a5 = np.random.randint(10, size=(4, 2))
a6 = np.random.randint(10, size=(4, 2))
a5,a6

(array([[9, 4],
        [0, 1],
        [9, 0],
        [1, 8]]),
 array([[9, 0],
        [8, 6],
        [4, 3],
        [0, 4]]))

In [64]:
# Compare the two arrays with '>'
a5 > a6

array([[False,  True],
       [False, False],
       [ True, False],
       [ True,  True]])

What happens when you compare the arrays with `>`?

In [65]:
# Compare the two arrays with '>='
a5 >= a6

array([[ True,  True],
       [False, False],
       [ True, False],
       [ True,  True]])

In [66]:
# Find which elements of the first array are greater than 7
a5 > 7

array([[ True, False],
       [False, False],
       [ True, False],
       [False,  True]])

In [67]:
# Which parts of each array are equal? (try using '==')
a5 == a6

array([[ True, False],
       [False, False],
       [False, False],
       [False, False]])

In [80]:
# Sort one of the arrays you just created in ascending order
np.sort(a5)

array([[4, 9],
       [0, 1],
       [0, 9],
       [1, 8]])

In [81]:
# Sort the indexes of one of the arrays you just created
np.argsort(a6)

array([[1, 0],
       [1, 0],
       [1, 0],
       [0, 1]], dtype=int64)

In [82]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a5)

1

In [83]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a5)

2

In [85]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(a6,axis= 1)

array([0, 0, 0, 1], dtype=int64)

In [86]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(a6,axis=0)

array([3, 0], dtype=int64)

In [91]:
# Create an array of normally distributed random numbers
normal_dist_array = np.random.randn(5, 5)
normal_dist_array

array([[ 0.61122978, -0.20360308, -0.52417382, -0.41857402, -0.06191621],
       [-1.05884829,  1.80524558, -0.07402322,  2.2048857 , -0.45208929],
       [-0.20943596, -0.29468436,  0.90649216,  0.99925449,  0.31538431],
       [ 1.13779947,  1.15809636,  0.99976052, -0.41644862, -1.1437764 ],
       [-1.62644682, -1.45878942, -0.31582535, -1.28893581, -0.10835998]])

In [93]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,num = 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in doubt, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.